python search.py \
--task 'node_level' \
--data 'AmazonComputer' \
--nb_classes 10 \
--data_clip 1.0 \
--in_dim_V 767 \
--batch 32 \
--node_dim 128 \
--pos_encode 0 \
--nb_layers 3 \
--nb_nodes  2 \
--dropout 0.2 \
--portion 0.5 \
--search_mode 'train' \
--nb_workers 0 \
--report_freq 1 \
--arch_save 'archs/folder5' \
--batchnorm_op \
--log_name 'node_AmazonComputer_search.log' \
--epoch 200